# Generated by Django 3.0.4 on 2020-04-08 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_realtimedata_stockinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daydata',
            old_name='chg_price',
            new_name='AdjClose',
        ),
        migrations.RenameField(
            model_name='daydata',
            old_name='close_price',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='daydata',
            old_name='d_date',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='daydata',
            old_name='netchg',
            new_name='High',
        ),
        migrations.AddField(
            model_name='daydata',
            name='Low',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daydata',
            name='Open',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daydata',
            name='Volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
