# Generated by Django 3.0.4 on 2020-04-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20200408_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('AdjClose', models.FloatField()),
                ('Volume', models.FloatField()),
                ('stockinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.StockInfo')),
            ],
        ),
    ]
